[project]
name = "project09"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.44.1",
    "matplotlib>=3.7.0",
    "pandas>=2.0.0",
]
